language: python
env:
  global:
    - DEPLOY_PROD_PATH=/var/www/help/faq-glossary/
    - DEPLOY_BETA_PATH=/var/www/betahelp/faq-glossary/
python:
  - 2.7
install:
  - pip install -r requirements.txt
script:
  - rm -rf build/ tmp/
  - sphinx-build -aE -nW -Dlanguage='en' -b html -d tmp source/ build/en
  - sphinx-build -aE -nW -Dlanguage='fr' -b html -d tmp source/ build/fr
  - sphinx-build -aE -nW -Dlanguage='es' -b html -d tmp source/ build/es
  - sphinx-build -aE -nW -Dlanguage='de' -b html -d tmp source/ build/de
  - sphinx-build -aE -nW -Dlanguage='nl' -b html -d tmp source/ build/nl
after_success:
  # - openssl aes-256-cbc -K $encrypted_83dcc4e2814b_key -iv $encrypted_83dcc4e2814b_iv -in .travis.deploy.enc -out .travis.deploy -d
  - chmod 600 .travis.deploy
  - 'test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "develop" && rsync -avz -e "ssh -i .travis.deploy -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" --delete -P build/ "$DEPLOY_USER"@"$DEPLOY_IP":"$DEPLOY_BETA_PATH"'
  - 'test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && rsync -avz -e "ssh -i .travis.deploy -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" --delete -P build/ "$DEPLOY_USER"@"$DEPLOY_IP":"$DEPLOY_PROD_PATH"'
sudo: false
notifications:
  slack:
    secure: APEJ/vt/8HAE8OWGR3DfL+XBQl4/Q35nN216+cFmuSHKuniV+XwLkvM3sEIC5OPABsxg/37oqoYr0a39PHyGQvBZ5ie9s9LpUsXUd76QgDZzR9BYxid9Atg2KXGqn2vrxJ8ZyKkQyd6VivJ8TtX8hlRsTZsx7fmbDqr9omzDldg=
